### ISSUE TITLE
Possibly add torchvision==0.11.0+cu113 and librosa==0.8.1 to requirements.txt.

### ISSUE THREAD

**Issue by zz-xx** [innnky/so-vits-svc#168]
From my experience in setting up on Windows 11 these requirements are must to run. Especially any version after librosa==0.8.1 is incompatible. Can possibly be added to requirements.txt to save future users from errors that happen while executing resample.py and preprocess_hubert_f0.py.

**Comment by Anomyous1** [comment]
current .txt looks like below
!pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu113    
also seems to work so im not sure if it depends on cuda version or what. in theory it should be possible to generate based on your environment but i've nver seen that. im not even sure if it works on 11.3 since ive been using 11.6

Flask
Flask_Cors
gradio
numpy==1.22.4
pyworld==0.3.2
scipy==1.7.3
SoundFile==0.12.1
torch==1.13.1
torchaudio==0.13.1
tqdm
scikit-maad
praat-parselmouth
onnx
onnxsim
onnxoptimizer
fairseq==0.12.2
librosa==0.8.1

**Comment by zz-xx** [comment]
Closing this as 4.0 branch has separate "requirements_win.txt" which solves problem. This issue is for 3.0 branch on windows if someone comes across this.
