### ISSUE TITLE
Resampling not working in Colab training notebook

### ISSUE THREAD

**Issue by Broccaloo** [innnky/so-vits-svc#72]
Hello, 

the `!python resample.py` step doesn't seem to work properly in the training notebook.
It only returns `./dataset_raw/content
0it [00:00, ?it/s]` but doesn't actually do anything. 

Because of this, the next cell with `!python preprocess_flist_config.py` returns `Traceback (most recent call last):
  File "preprocess_flist_config.py", line 84, in <module>
    for speaker in tqdm(os.listdir(args.source_dir)):
FileNotFoundError: [Errno 2] No such file or directory: './dataset/32k'`

**Comment by bilbillm** [comment]
I have the same problem.
the !python resample.py step return nothing

Then the next step is the same mistake as you

My audio is converted to 32k format with other converters and then uploaded to the google drive

**Comment by YuguiYaoyao** [comment]
resample.py 没有返回是因为你的DataSet_raw文件夹下的文件树不对，看colab里面的笔记也可知代码需要的文件夹结构应该是./dataset_raw/${说话人名称}/${音频文件名称}.wav，音频文件要放在dataset_raw下面的文件夹里才会被检测到

看resample.py代码也可以知道代码逻辑是检测dataset_raw下面的文件夹然后再从文件夹中提取音频的，应该是为了训练多说话人方便一些

resample.py is not returned because the file tree under your DataSet_raw folder is not correct, look at the notes inside colab also know that the folder structure needed by resample.py should be like ‘. /dataset_raw/${speaker name}/${audio file name}.wav’, audio files should be placed in the folder under dataset_raw so that wavs could be detected

Looking through the resample.py code, you can also see that the code is aimed to
detect the folder under dataset_raw and then use the audio in that folder, which is supposed to be convenient for training more than one speaker.

**Comment by Broccaloo** [comment]
Ok, I have gotten this to work by adding an extra cell copying over the folder to the correct place like this: `!cp -av '/content/so-vits-svc/dataset_raw/content/drive/MyDrive/dataset/test' '/content/so-vits-svc/dataset_raw'`
Of course you need to replace "test" with the name of your folder. Without this extra line of code, it wouldn't work for me. Hoping this helps other people with the same problem!

**Comment by Leifybearjonesy** [comment]
I'm stuck on the exact same issue with FileNotFoundError: [Errno 2] No such file or directory: './dataset/32k' being returned. I tried Broccaloo's suggestion; however, this also returns with No such file or directory despite test being the name of my folder.

**Comment by yang-code1** [comment]
> I'm stuck on the exact same issue with FileNotFoundError: [Errno 2] No such file or directory: './dataset/32k' being returned. I tried Broccaloo's suggestion; however, this also returns with No such file or directory despite test being the name of my folder.

cd so-vits-svc
mkdir ./dataset_raw/‘speaker name’ 
(move the data to this folder)
mkdir ./dataset/32k
